name: build & test

on: [push, pull_request]

jobs:
  build-bitstream-icebreaker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: YosysHQ/setup-oss-cad-suite@v1
      - run: git submodule update --init gateware/external/no2misc
      - run: yosys --version
      - run: make BOARD=icebreaker -C gateware
      - uses: actions/upload-artifact@v3
        with:
          name: eurorack-pmod-bitstream.bin
          path: gateware/top.bin

  build-bitstream-colorlight-i5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: YosysHQ/setup-oss-cad-suite@v1
      - run: git submodule update --init gateware/external/no2misc
      - run: yosys --version
      - run: make BOARD=colorlight_i5 -C gateware
      - uses: actions/upload-artifact@v3
        with:
          name: eurorack-pmod-bitstream.bin
          path: gateware/top.bin

  build-bitstream-colorlight-i9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: YosysHQ/setup-oss-cad-suite@v1
      - run: git submodule update --init gateware/external/no2misc
      - run: yosys --version
      - run: make BOARD=colorlight_i9 -C gateware
      - uses: actions/upload-artifact@v3
        with:
          name: eurorack-pmod-bitstream.bin
          path: gateware/top.bin

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: YosysHQ/setup-oss-cad-suite@v1
      - run: git submodule update --init gateware/external/no2misc
      - run: cocotb-config -v
      - run: cd gateware/sim && ./00_run.sh

  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: YosysHQ/setup-oss-cad-suite@v1
      - run: git submodule update --init gateware/external/no2misc
      - run: verilator --version
      - run: cd gateware && scripts/verilator_lint.sh
